// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoDN55vPwDLSwrhRNm0WePTHbHnptXbT8',
    appId: '1:374221639683:web:10a2ed9d9e07c8e08dfe36',
    messagingSenderId: '374221639683',
    projectId: 'e-commerce-95c20',
    authDomain: 'e-commerce-95c20.firebaseapp.com',
    storageBucket: 'e-commerce-95c20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPmn02rBMUINglZox1k71N_gTIOUaFTG8',
    appId: '1:374221639683:android:12d576db3b29c4fe8dfe36',
    messagingSenderId: '374221639683',
    projectId: 'e-commerce-95c20',
    storageBucket: 'e-commerce-95c20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAps52tJtx5w_PBWkH92-BTHQ0g4Bw-Qxo',
    appId: '1:374221639683:ios:e97e4a1f0fefa7ca8dfe36',
    messagingSenderId: '374221639683',
    projectId: 'e-commerce-95c20',
    storageBucket: 'e-commerce-95c20.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAps52tJtx5w_PBWkH92-BTHQ0g4Bw-Qxo',
    appId: '1:374221639683:ios:e97e4a1f0fefa7ca8dfe36',
    messagingSenderId: '374221639683',
    projectId: 'e-commerce-95c20',
    storageBucket: 'e-commerce-95c20.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoDN55vPwDLSwrhRNm0WePTHbHnptXbT8',
    appId: '1:374221639683:web:321826193b8bd27d8dfe36',
    messagingSenderId: '374221639683',
    projectId: 'e-commerce-95c20',
    authDomain: 'e-commerce-95c20.firebaseapp.com',
    storageBucket: 'e-commerce-95c20.appspot.com',
  );
}
